apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
    kind: Deployment
    metadata:
      name: &app_name
          basic-http-server-python
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: *app_name
        spec:
          containers:
          - name: *app_name
            image: beardedfoo/basic-http-server-python
            imagePullPolicy: Always
            ports:
            - containerPort: 80
            livenessProbe:
                httpGet:
                    path: /healthz
                    port: 80
                initialDelaySeconds: 3
                timeoutSeconds: 5
                failureThreshold: 2
  - apiVersion: v1
    kind: Service
    metadata:
      name: *app_name
    spec:
      selector:
        app: *app_name
      ports:
        - protocol: TCP
          port: 80
          targetPort: 80
